### ISSUE TITLE
Improve components.md

### ISSUE THREAD

**Issue by typicode** [typicode/react-lodash#1]
To make `components.md` a little more useful, it would be great to add some more informatin.

__Add prop names__

Modify https://github.com/typicode/react-lodash/blob/master/generate/index.js#L62-L71 to add prop names.

For example, should render `<Add augend addend />` instead of just `<Add />`.

__Add link to lodash doc__

Next to the component, it would be good to have a link do lodash doc.

For example, `<Add ... />`  [_.add](https://lodash.com/docs/4.17.10#add)

**Comment by rkkautsar** [comment]
✋ I'll try implementing these
